### ISSUE TITLE
Refactor scripts in  scripts/

### ISSUE THREAD

**Issue by npotts** [ncareol/isfs#2]
Before I go ahead and break everything, I would like to see what people are using.

# isfs.bashrc
- This looks to be nothing but aliases and a lazy import of isfs_functions.sh
- are these alias absolutely necessary? 
    - EG, if I have 'h' already aliased to a function that does something else, will it break something?
    - are ```ds``` and ```md``` required?
    - my intent is not to remove them, but understand how they are used.  I don't want to clutter my own environment with 2 letter commands NIDAS may uses but I already have assigned to other functions.

# isfs_functions.sh

- Can we add some sort of usage or warning if environmental vars are not set?  I would like to add the following at the head (or similar):
```sh
isfs_local_checks() {
    if [ -z "${ISFS}" ]; then
        echo You need to set \$ISFS to wherever you checked out github.com/ncareol/isfs
        echo Refusing to do anything until that is fixed 
        return
    fi

    if [ -z "${PROJECT}" ]; then
	echo No \$PROJECT has been set.  Run 'set_project' or export \$PROJECT
    fi
}
isfs_local_checks
```
- add some basic changes for non-GNU coreutils, BSD flags and all that
- Add additional prunes to the ```find``` in set_project.  Right now it thinks. ```.git``` and ```python``` folders are projects

**Comment by oncley** [comment]
PLEASE, NO!  For decades (i.e., before svn, git, etc.), we've had a
"static" $ISFS tree at /net/isf/isfs/, which I, at least, still use.

"ds" and "md" are used every time that field staff log in to a DSM.

We can talk, but I'm getting really weary of daily hacking away on stuff
that we've spent years putting together...Steve

**Comment by npotts** [comment]
Steve, 
this is why I am asking.

Nothing in that script sets ISFS to anything, but rather just silently fails if $ISFS *isnt* set.
